### ISSUE TITLE
Are net_core_compat binaries production ready?

### ISSUE THREAD

**Issue by vokounjan** [ams-tschoening/ikvm-bin#2]
First of all - thank you for reviving this project.

I need to use one Java library in a .NET Core project and the the binaries from _net_core_compat_ branch have worked without any issue so far so I'd like to stick to them but the fact that they've not been released oficially (via GitHub release or NuGet) is quite suspicious. Is it "safe" to use them? Is there anything I should be aware of before using them?

Thank you for your response.

**Comment by ams-tschoening** [comment]
This repo is part of a PoC I needed at work for myself only and I therefore have no plans to "officially" release anything. The next best "official" thing around IKVM is available in the organisation [ikvm-revived](https://github.com/ikvm-revived), not here. There simply haven't been too much demand currently to move this repo there or alike.

So, using my work is simply at your own risk. I wasn't able to work on my PoC for months anymore as well, so one might even consider it abandoned. I'm NOT using it in production myself, mainly because an UWP app build with my binaries can't be published to the MS App Store currently. The following is an overview of open issues:

* https://github.com/ikvm-revived/ikvm/issues/1
* https://github.com/ikvm-revived/ikvm/issues/3
* https://github.com/ikvm-revived/ikvm/issues/6

It's up to you to decide if you want to take the risk or have any better alternatives. But be aware that if you run into any trouble, I won't be able to help most likely. Instead, you should discuss things in [ikvm-revived](https://github.com/ikvm-revived) and/or need to debug problems mostly on your own, hopefully publishing your solutions as well afterwards. Good luck anyway!
